name: Edit
description: Edit a package
title: "Edit: "
labels: [edit]
assignees:
  - Toxikuu
body:
  - type: markdown
    attributes:
      value: |
        ## Edit

  - type: input
    id: name
    attributes:
      label: Name
      description: The name of the package
      placeholder: curl
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How badly do the edits need to be made?
      options: [1, 2, 3, 4, 5, 6, 7, 8, 9]
      default: 0
    validations:
      required: false

  - type: textarea
    id: edits
    attributes:
      label: Edits
      description: The edits that should be made, preferably with rationale
      render: markdown
      placeholder: |
        Completely rewrite the awful build instructions. This should be done because they are awful.
    validations:
      required: true
