# /etc/tldr/config.toml
# Tealdeer config

[style.description]
underline = false
bold = false
italic = true

[style.command_name]
foreground = "cyan"
underline = false
bold = false
italic = false

[style.example_text]
foreground = "green"
underline = false
bold = false
italic = false

[style.example_code]
foreground = "cyan"
underline = false
bold = false
italic = false

[style.example_variable]
foreground = "cyan"
underline = true
bold = false
italic = false

[display]
compact = false
use_pager = false

[updates]
auto_update = true
auto_update_interval_hours = 720

# `/var/cache/tldr` is used as a single global cache
[directories]
cache_dir = "/var/cache/tldr"
